In [50]:
print("hi")

hi


In [51]:
# !pip install tensorflow


In [52]:
!python --version

Python 3.10.13


# Importing Libraries


In [53]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns   



### Data preprocessing

Trainig Image Preprocessing

In [54]:
training_set=tf.keras.utils.image_dataset_from_directory(
    'C:\\Users\\FA0555TX\\Downloads\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


Validation Image Preprocessing

In [55]:
validation_set=tf.keras.utils.image_dataset_from_directory(
    'C:\\Users\\FA0555TX\\Downloads\\New Plant Diseases Dataset(Augmented)\\New Plant Diseases Dataset(Augmented)\\valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


In [56]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [57]:
validation_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [58]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[127.75 116.75 120.75]
   [140.   129.   133.  ]
   [135.75 124.75 128.75]
   ...
   [165.5  156.5  159.5 ]
   [177.75 168.75 171.75]
   [174.   165.   168.  ]]

  [[120.25 109.25 113.25]
   [131.5  120.5  124.5 ]
   [135.75 124.75 128.75]
   ...
   [170.75 161.75 164.75]
   [178.   169.   172.  ]
   [166.5  157.5  160.5 ]]

  [[123.25 112.25 116.25]
   [112.25 101.25 105.25]
   [127.   116.   120.  ]
   ...
   [173.   164.   167.  ]
   [170.   161.   164.  ]
   [167.25 158.25 161.25]]

  ...

  [[193.5  186.5  193.5 ]
   [189.5  182.5  189.5 ]
   [186.5  179.5  186.5 ]
   ...
   [191.   182.   187.  ]
   [194.5  185.5  190.5 ]
   [191.75 182.75 187.75]]

  [[187.5  180.5  187.5 ]
   [190.25 183.25 190.25]
   [191.75 184.75 191.75]
   ...
   [190.5  181.5  186.5 ]
   [191.75 182.75 187.75]
   [193.25 184.25 189.25]]

  [[185.25 178.25 185.25]
   [190.   183.   190.  ]
   [190.5  183.5  190.5 ]
   ...
   [191.5  182.5  187.5 ]
   [188.5  179.5  184.5 ]
   [191.   182.   18

# Model

In [59]:
from tensorflow.keras.layers import Conv2D,Dense,MaxPool2D,Flatten,Dropout
from tensorflow.keras.models import Sequential

In [60]:
model=Sequential()

In [61]:
## Layers
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[128,128,3]))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [62]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu',))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [63]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu',))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [64]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu',))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [65]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu',))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [66]:
model.add(Dropout(0.25))

In [67]:
model.add(Flatten())

In [68]:
model.add(Dense(units=1500,activation='relu'))

In [69]:
model.add(Dropout(0.4))

In [70]:
## Output Layer
model.add(Dense(units=38,activation='softmax'))

### Compiling Model

In [71]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [72]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d_20 (Conv2D)              │ (None, 128, 128, 32)   │           896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_21 (Conv2D)              │ (None, 126, 126, 32)   │         9,248 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_10 (MaxPooling2D) │ (None, 63, 63, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_22 (Conv2D)              │ (None, 63, 63, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_23 (Conv2D)              │ (None, 61, 61, 64)     │        36,928 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_11 (MaxPooling2D) │ (None, 30, 30, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_24 (Conv2D)              │ (None, 30, 30, 128)    │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_25 (Conv2D)              │ (None, 28, 28, 128)    │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_12 (MaxPooling2D) │ (None, 14, 14, 128)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_26 (Conv2D)              │ (None, 14, 14, 256)    │       295,168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_27 (Conv2D)              │ (None, 12, 12, 256)    │       590,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_13 (MaxPooling2D) │ (None, 6, 6, 256)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_28 (Conv2D)              │ (None, 6, 6, 512)      │     1,180,160 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_29 (Conv2D)              │ (None, 4, 4, 512)      │     2,359,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_14 (MaxPooling2D) │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 2, 2, 512)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_2 (Flatten)             │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1500)           │     3,073,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_5 (Dropout)             │ (None, 1500)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 38)             │        57,038 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 7,842,762 (29.92 MB)

 Trainable params: 7,842,762 (29.92 MB)

 Non-trainable params: 0 (0.00 B)

### Training Model

In [73]:
training_hist=model.fit(training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1105s 502ms/step - accuracy: 0.1032 - loss: 3.3419 - val_accuracy: 0.5749 - val_loss: 1.3601
Epoch 2/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 1230s 560ms/step - accuracy: 0.5936 - loss: 1.3013 - val_accuracy: 0.6642 - val_loss: 1.0422
Epoch 3/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 951s 433ms/step - accuracy: 0.7271 - loss: 0.8637 - val_accuracy: 0.7865 - val_loss: 0.6682
Epoch 4/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 950s 432ms/step - accuracy: 0.7838 - loss: 0.6749 - val_accuracy: 0.8090 - val_loss: 0.6015
Epoch 5/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 949s 432ms/step - accuracy: 0.8063 - loss: 0.6007 - val_accuracy: 0.8142 - val_loss: 0.5913
Epoch 6/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 947s 431ms/step - accuracy: 0.8270 - loss: 0.5332 - val_accuracy: 0.8411 - val_loss: 0.4951
Epoch 7/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 970s 442ms/step - accuracy: 0.8389 - loss: 0.4957 - val_accuracy: 0.8446 - val_loss: 0.4692
Epoch 8/10
2197/2197 ━━━━━━━━━━━━━━━━━━━━ 938s 427ms/step - 

In [74]:
#Training set Accuracy
train_loss, train_acc = model.evaluate(training_set)
print('Training accuracy:', train_acc)

2197/2197 ━━━━━━━━━━━━━━━━━━━━ 265s 120ms/step - accuracy: 0.8587 - loss: 0.4333
Training accuracy: 0.8651682138442993


In [75]:
#Validation set Accuracy
val_loss, val_acc = model.evaluate(validation_set)
print('Validation accuracy:', val_acc)

550/550 ━━━━━━━━━━━━━━━━━━━━ 66s 120ms/step - accuracy: 0.8255 - loss: 0.5430
Validation accuracy: 0.8228431344032288


In [76]:
# model.save('trained_plant_disease_model.keras')
# model.save('trained_plant_disease_model.h5')

In [83]:
model_version = 1
model.save(f"C:\\Users\\FA0555TX\\Desktop\\Minor Project{model_version}")

ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=C:\Users\FA0555TX\Desktop\Minor Project1.

In [87]:
import os
model_version=max([int(i) for i in os.listdir("C:\\Users\\FA0555TX\\Desktop\\Minor Project") + [0]])+1
model.save(f"C:\\Users\\FA0555TX\\Desktop\\Minor Project\\{model_version}")

ValueError: invalid literal for int() with base 10: 'api'

In [89]:
import os

# Filter out any non-integer named files/folders
file_versions = [int(i) for i in os.listdir("C:\\Users\\FA0555TX\\Desktop\\Minor Project") if i.isdigit()]
model_version = max(file_versions + [0]) + 1

# Save the model with the next available version number
model.save(f"C:\\Users\\FA0555TX\\Desktop\\Minor Project\\{model_version}")


ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=C:\Users\FA0555TX\Desktop\Minor Project\1.

In [93]:
# Specify the directory where you want to save the model
save_directory = "C:\\Users\\FA0555TX\\Desktop\\Minor Project\\saved_model_version"
model.save(save_directory, save_format="tf")


ValueError: The `save_format` argument is deprecated in Keras 3. Please remove this argument and pass a file path with either `.keras` or `.h5` extension.Received: save_format=tf

In [94]:
# Specify the directory where you want to save the model
save_directory = "C:\\Users\\FA0555TX\\Desktop\\Minor Project\\saved_model_version"
model.save(save_directory)


ValueError: Invalid filepath extension for saving. Please add either a `.keras` extension for the native Keras format (recommended) or a `.h5` extension. Use `model.export(filepath)` if you want to export a SavedModel for use with TFLite/TFServing/etc. Received: filepath=C:\Users\FA0555TX\Desktop\Minor Project\saved_model_version.

In [ ]:
# Specify the directory where you want to export the model
model_version = 1
export_directory = f"C:\\Users\\FA0555TX\\Desktop\\Minor Project\\{model_version}"
model.export(export_directory)


INFO:tensorflow:Assets written to: C:\Users\FA0555TX\Desktop\Minor Project\1\assets


INFO:tensorflow:Assets written to: C:\Users\FA0555TX\Desktop\Minor Project\1\assets


Saved artifact at 'C:\Users\FA0555TX\Desktop\Minor Project\1'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name='keras_tensor_422')
Output Type:
  TensorSpec(shape=(None, 38), dtype=tf.float32, name=None)
Captures:
  2286086925200: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2286021420384: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2286545501728: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2286021418096: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2286021419680: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2286031851536: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2286031861744: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2286031855408: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2286031852240: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2286052293296: TensorSpec(shape=(), dtype=tf.resource, name=None)
  2286